### ISSUE TITLE
Generate assertion for Object Type Application?

### ISSUE THREAD

**Issue by victor-homyakov** [azu/jsdoc-to-assert#16]
https://github.com/google/closure-compiler/wiki/Annotating-JavaScript-for-the-Closure-Compiler#type-application describes possible Type Application for Object: `Object<string, someType>`. It's easy to implement assert generation for this case as

```js
/**
 * @param {Object<string, number>} x
 */
```

=>

```js
Object.values(x).every(function (item) {
    return typeof item  === 'number';
});
```

AFAIK there is no need to generate assertion for first type (for object keys), as it will always be `string`.

If it looks good, then I'll make a PR.

**Comment by azu** [comment]
It looks good to me.

But, [Object.values()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/values "Object.values()") is not parts of current ECMAScript yet.
(It will be included in ECMAScript 2017. Some enviroment is not implemented yet.)

It is better that use `Object.keys(x)` instead of `Object.values(x)`, I think.

```js
Object.keys(x).every(function (key) {
    return typeof x[key]  === 'number';
});
```
